<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class Movie extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $movies = [
            [
                'movie_name' => 'Conan: Ngôi sao 5 cánh triệu đỏ',
                'describe' => 'Ông trùm suy luận, kẻ phá vỡ các lời biện minh xảo trá: Sherlockholmes',
                'category' => 'Hoạt hình',
                'images' => 'images/conan.jpg',
                'video' => 'video/conan.mp4',
                'age_limit' => false,
                'id_countries' => 1,
            ],
            [
                'movie_name' => 'Avenger infinity war',
                'describe' => 'Cuộc chiến vô cực',
                'category' => 'Khoa học viễn tưởng',
                'images' => 'images/avenger.jpg',
                'video' => 'video/avenger.mp4',
                'age_limit' => false,
                'id_countries' => 2,
            ],
            [
                'movie_name' => 'Doraemon: Nobita và bản giao hưởng địa cầu',
                'describe' => 'Cuộc phiêu lưu của con chồn và 4 người bạn',
                'category' => 'Hoạt hình',
                'images' => 'images/doraemon.jpg',
                'video' => 'video/doraemon.mp4',
                'age_limit' => false,
                'id_countries' => 3,
            ],
            [
                'movie_name' => 'Quật mộ trùng ma',
                'describe' => 'Chưa xem nên không biết mô tả như thế nào',
                'category' => 'Kinh dị',
                'images' => 'images/quatmo.jpg',
                'video' => 'video/quatmo.mp4',
                'age_limit' => true,
                'id_countries' => 4,
            ],
            [
                'movie_name' => 'Sherlockholmes phiêu lưu kí',
                'describe' => 'Chưa xem nên không biết mô tả như thế nào',
                'category' => 'Hình sự',
                'images' => 'images/sherlockholmes.jpg',
                'video' => 'video/sherlockholmes.mp4',
                'age_limit' => true,
                'id_countries' => 5,
            ],
            [
                'movie_name' => 'Nhà có 5 nàng dâu movie',
                'describe' => 'Yotsubaaaa thua thế *** nào được',
                'category' => 'Lãng mạn',
                'images' => 'images/5nangdau.jpg',
                'video' => 'video/5nangdau.mp4',
                'age_limit' => false,
                'id_countries' => 6,
            ],
            [
                'movie_name' => 'Gửi em nguời bất tử',
                'describe' => 'Đơn giản thì anh không thể chết',
                'category' => 'Phiêu lưu',
                'images' => 'images/toyoureternity.jpg',
                'video' => 'video/toyoureternity.mp4',
                'age_limit' => true,
                'id_countries' => 7,
            ],
            [
                'movie_name' => 'Nguời mẹ tồi của tôi',
                'describe' => 'Hành trình trả thù của thằng nhóc 30 tuổi',
                'category' => 'Tâm lý',
                'images' => 'images/thegodbadmother.jpg',
                'video' => 'video/thegodbadmother.mp4',
                'age_limit' => false,
                'id_countries' => 8,
            ],
            [
                'movie_name' => 'Trở lại tuổi 18',
                'describe' => 'Đầu thai trở lại 18 tuổi để cua lại vợ cũ',
                'category' => 'Lãng mạn',
                'images' => 'images/18again.jpeg',
                'video' => 'video/18again.mp4',
                'age_limit' => false,
                'id_countries' => 1,
            ],
            [
                'movie_name' => 'Your name',
                'describe' => 'Cua gái vượt cả thời đại',
                'category' => 'Lãng mạn',
                'images' => 'images/yourname.jpg',
                'video' => 'video/yourname.mp4',
                'age_limit' => false,
                'id_countries' => 2,
            ],
            [
                'movie_name' => 'Tuổi trẻ của tháng năm',
                'describe' => 'Tất cả tại lũ hàn xẻng',
                'category' => 'Lãng mạn',
                'images' => 'images/youthofmay.jpg',
                'video' => 'video/youthofmay.mp4',
                'age_limit' => false,
                'id_countries' => 3,
            ],
            [
                'movie_name' => 'The Shape of Water',
                'describe' => 'Một câu chuyện tình lãng mạn giữa một nhân viên vệ sinh câm và một sinh vật thủy sinh bị giam giữ trong phòng thí nghiệm của chính phủ vào những năm 1960.',
                'category' => 'Lãng mạn',
                'images' => 'images/theshapeofwater.jpg',
                'video' => 'video/theshapeofwater.mp4',
                'age_limit' => true,
                'id_countries' => 4,
            ],
            [
                'movie_name' => 'La La Land',
                'describe' => 'Một nhạc sĩ jazz và một nữ diễn viên đầy tham vọng cố gắng dung hòa tình yêu của họ với sự nghiệp cá nhân trong thế giới đầy màu sắc của Los Angeles.',
                'category' => 'Lãng mạn',
                'images' => 'images/lalaland.jpg',
                'video' => 'video/lalaland.mp4',
                'age_limit' => false,
                'id_countries' => 5,
            ],
            [
                'movie_name' => 'Her',
                'describe' => 'Một người đàn ông cô đơn phát triển một mối quan hệ lãng mạn với hệ điều hành trí tuệ nhân tạo tiên tiến, khám phá tình yêu và sự cô đơn trong thế giới hiện đại.',
                'category' => 'Lãng mạn',
                'images' => 'images/her.jpg',
                'video' => 'video/her.mp4',
                'age_limit' => true,
                'id_countries' => 6,
            ],
            [
                'movie_name' => '12 Years a Slave',
                'describe' => 'Dựa trên câu chuyện có thật về Solomon Northup, một người đàn ông da đen tự do bị bắt cóc và bán vào chế độ nô lệ ở miền Nam nước Mỹ vào thế kỷ 19.',
                'category' => 'Tâm lý',
                'images' => 'images/12yearaslave.jpg',
                'video' => 'video/12yearaslave.mp4',
                'age_limit' => true,
                'id_countries' => 7,
            ],
            [
                'movie_name' => 'Django Unchained',
                'describe' => 'Một nô lệ được trả tự do trở thành thợ săn tiền thưởng và hợp tác với một thợ săn tiền thưởng người Đức để giải cứu vợ mình khỏi một tên chủ đồn điền độc ác.',
                'category' => 'Hành động',
                'images' => 'images/djangounchained.jpg',
                'video' => 'video/djangounchained.mp4',
                'age_limit' => true,
                'id_countries' => 8,
            ],
            [
                'movie_name' => 'Moonlight',
                'describe' => 'Bộ phim theo chân cuộc đời của một người đàn ông da đen từ thời thơ ấu đến khi trưởng thành, khám phá các chủ đề về bản sắc, gia đình, và tình yêu trong một cộng đồng khó khăn ở Miami.',
                'category' => 'Tâm lý',
                'images' => 'images/moonlight.jpg',
                'video' => 'video/moonlight.mp4',
                'age_limit' => true,
                'id_countries' => 1,
            ],
            [
                'movie_name' => 'The Social Network',
                'describe' => 'Câu chuyện về sự ra đời của Facebook và sự kiện pháp lý liên quan đến việc sáng lập, tập trung vào Mark Zuckerberg và những người bạn học tại Harvard.',
                'category' => 'Tâm lý',
                'images' => 'images/thesocialnetwork.jpg',
                'video' => 'video/thesocialnetwork.mp4',
                'age_limit' => false,
                'id_countries' => 2,
            ],
            [
                'movie_name' => 'Whiplash',
                'describe' => 'Một tay trống trẻ đầy tham vọng đăng ký vào một nhạc viện danh tiếng, nơi anh ta bị một giáo viên khắc nghiệt và bạo lực thử thách đến mức cực đoan.',
                'category' => 'Tâm lý',
                'images' => 'images/whiplash.jpg',
                'video' => 'video/whiplash.mp4',
                'age_limit' => false,
                'id_countries' => 3,
            ],
            [
                'movie_name' => 'Dunkirk',
                'describe' => 'Một bộ phim chiến tranh mô tả cuộc di tản của hàng trăm ngàn binh sĩ Đồng minh bị mắc kẹt tại bãi biển Dunkirk trong Thế chiến II.',
                'category' => 'Tâm lý',
                'images' => 'images/dunkirk.jpg',
                'video' => 'video/dunkirk.mp4',
                'age_limit' => false,
                'id_countries' => 4,
            ],
            [
                'movie_name' => 'Manchester by the Sea',
                'describe' => 'Một người đàn ông bị ám ảnh bởi quá khứ bi kịch phải trở về quê hương để chăm sóc cháu trai sau cái chết của anh trai.',
                'category' => 'Tâm lý',
                'images' => 'images/manchesterbythesea.jpg',
                'video' => 'video/manchesterbythesea.mp4',
                'age_limit' => false,
                'id_countries' => 5,
            ],
            [
                'movie_name' => 'Spotlight',
                'describe' => 'Một nhóm phóng viên của tờ Boston Globe điều tra vụ bê bối lạm dụng tình dục trong Nhà thờ Công giáo, dẫn đến một loạt các phát hiện gây chấn động.',
                'category' => 'Tâm lý',
                'images' => 'images/spotlight.jpg',
                'video' => 'video/spotlight.mp4',
                'age_limit' => false,
                'id_countries' => 6,
            ],
            [
                'movie_name' => 'Boyhood',
                'describe' => 'Bộ phim quay trong suốt 12 năm, kể về cuộc sống của một cậu bé từ tuổi thơ đến khi trưởng thành, với những thay đổi trong gia đình và cuộc sống xung quanh.',
                'category' => 'Tâm lý',
                'images' => 'images/boyhood.jpg',
                'video' => 'video/boyhood.mp4',
                'age_limit' => false,
                'id_countries' => 7,
            ],
            [
                'movie_name' => 'Shin: Huyền thoại ninja Mononoke',
                'describe' => 'Shinnosuke, cùng với gia đình và bạn bè, bước vào một cuộc phiêu lưu đầy thử thách để chống lại các thế lực đen tối. Trong hành trình này, cậu học được những kỹ năng ninja, khám phá ra sức mạnh tiềm ẩn bên trong mình và đối mặt với những kẻ thù nguy hiểm.',
                'category' => 'Hoạt hình',
                'images' => 'images/shinmovie30.jpg',
                'video' => 'video/shinmovie30.mp4',
                'age_limit' => false,
                'id_countries' => 8,
            ],
            [
                'movie_name' => 'Shin: Cuộc xâm lăng của người ngoài hành tinh Shiriri',
                'describe' => 'Trong cuộc phiêu lưu đầy hài hước và kịch tính này, họ khám phá ra những bí mật về Shiriri và học cách đoàn kết để vượt qua khó khăn.',
                'category' => 'Hoạt hình',
                'images' => 'images/shinmovie25.jpg',
                'video' => 'video/shinmovie25.mp4',
                'age_limit' => false,
                'id_countries' => 1,
            ],
            [
                'movie_name' => 'Shin: Kungfu Boys – Mì Ramen đại chiến',
                'describe' => 'Trong bối cảnh một cuộc thi nấu mì ramen lớn diễn ra, Shin-chan và nhóm bạn quyết định tham gia để giành chiến thắng.',
                'category' => 'Hoạt hình',
                'images' => 'images/shinmovie26.png',
                'video' => 'video/shinmovie26.mp4',
                'age_limit' => false,
                'id_countries' => 2,
            ],
            [
                'movie_name' => 'Doraemon: Nobita và đảo giấu vàng',
                'describe' => 'Trong bộ phim này, Nobita và nhóm bạn cùng với Doraemon bị cuốn vào một cuộc phiêu lưu hấp dẫn đến một hòn đảo bí mật được cho là chứa đầy kho báu.',
                'category' => 'Hoạt hình',
                'images' => 'images/doraemonmovie38.jpg',
                'video' => 'video/doraemonmovie38.mp4',
                'age_limit' => false,
                'id_countries' => 3,
            ],
            [
                'movie_name' => 'Doraemon: Nobita và chuyến thám hiểm Nam Cực Kachi Kochi',
                'describe' => 'Trên tàu hỏa đặc biệt "Doraemon Express", Nobita và nhóm bạn cùng với Doraemon bắt đầu cuộc hành trình đến Nam Cực - một vùng đất lạnh giá tuyệt đẹp.',
                'category' => 'Hoạt hình',
                'images' => 'images/doraemonmovie37.jpg',
                'video' => 'video/doraemonmovie37.mp4',
                'age_limit' => false,
                'id_countries' => 4,
            ],
            [
                'movie_name' => 'Conan: Tàu ngầm sắt màu đen',
                'describe' => 'Câu chuyện bắt đầu khi một nhóm người lạ mặt tham gia chuyến đi trên tàu ngầm, nhưng sự kiện trở nên bí ẩn khi một vụ án mạng đột ngột xảy ra. Conan và các bạn của mình bắt đầu điều tra để tìm ra kẻ thủ ác và lời giải cho bí ẩn trên chiếc tàu ngầm sắt màu đen này.',
                'category' => 'Hoạt hình',
                'images' => 'images/conanmove26.jpg',
                'video' => 'video/conanmove26.mp4',
                'age_limit' => false,
                'id_countries' => 5,
            ],
            [
                'movie_name' => 'Conan: Nàng dâu Halloween',
                'describe' => ' Conan Edogawa và nhóm thám tử nhí phải giải quyết một vụ án mạng xảy ra trong một lễ hội Halloween.',
                'category' => 'Hoạt hình',
                'images' => 'images/conanmovie25.jpg',
                'video' => 'video/conanmovie25.mp4',
                'age_limit' => false,
                'id_countries' => 6,
            ],
            [
                'movie_name' => 'Ký Sinh Trùng',
                'describe' => 'Một gia đình nghèo khó xâm nhập vào cuộc sống của một gia đình giàu có bằng cách giả danh làm người giúp việc và giáo viên tư gia. Bộ phim khám phá sự phân tầng xã hội và khoảng cách giàu nghèo.',
                'category' => 'Kinh dị',
                'images' => 'images/parasite.jpg',
                'video' => 'video/parasite.mp4',
                'age_limit' => true,
                'id_countries' => 7,
            ],
            [
                'movie_name' => 'Inception',
                'describe' => 'Một chuyên gia ăn cắp thông tin bằng cách xâm nhập vào giấc mơ của người khác phải thực hiện một nhiệm vụ cấy ghép ý tưởng vào tiềm thức của mục tiêu.',
                'category' => 'Hành động',
                'images' => 'images/inception.jpg',
                'video' => 'video/inception.mp4',
                'age_limit' => false,
                'id_countries' => 8,
            ],
            [
                'movie_name' => 'The Grand Budapest Hotel',
                'describe' => 'Một câu chuyện về một nhân viên lễ tân và người học việc của ông ta tại một khách sạn nổi tiếng trong thời kỳ giữa hai cuộc thế chiến, với nhiều tình tiết hài hước và ly kỳ.',
                'category' => 'Hài',
                'images' => 'images/thegradbudapesthotel.jpg',
                'video' => 'video/thegradbudapesthotel.mp4',
                'age_limit' => false,
                'id_countries' => 1,
            ],
            [
                'movie_name' => 'Birdman',
                'describe' => 'Một diễn viên hết thời, từng nổi tiếng với vai siêu anh hùng, cố gắng tái thiết lập sự nghiệp của mình bằng cách sản xuất và đóng vai chính trong một vở kịch trên Broadway.',
                'category' => 'Hài',
                'images' => 'images/birdman.jpg',
                'video' => 'video/birdman.mp4',
                'age_limit' => true,
                'id_countries' => 2,
            ],
            [
                'movie_name' => 'The Revenant',
                'describe' => 'Một thợ săn vùng biên giới bị bỏ rơi sau khi bị gấu tấn công phải chiến đấu để sống sót và trả thù những kẻ đã phản bội anh ta.',
                'category' => 'Phiêu lưu',
                'images' => 'images/therevenant.jpg',
                'video' => 'video/therevenant.mp4',
                'age_limit' => true,
                'id_countries' => 3,
            ],
            [
                'movie_name' => 'Mad Max: Fury Road',
                'describe' => 'Trong một thế giới hậu tận thế, Max cùng với Imperator Furiosa chống lại một tên lãnh chúa tàn bạo để giành lấy tự do cho những người bị đàn áp.',
                'category' => 'Khoa học viễn tưởng',
                'images' => 'images/madmaxfuryroad.jpg',
                'video' => 'video/madmaxfuryroad.mp4',
                'age_limit' => false,
                'id_countries' => 4,
            ],
            [
                'movie_name' => 'The Wolf of Wall Street',
                'describe' => 'Câu chuyện có thật về Jordan Belfort, từ một nhà môi giới chứng khoán trẻ tuổi đầy tham vọng đến một tỷ phú trụy lạc, cuối cùng bị pháp luật bắt giữ.',
                'category' => 'Hài',
                'images' => 'images/thewolfofwallstreet.jpg',
                'video' => 'video/thewolfofwallstreet.mp4',
                'age_limit' => true,
                'id_countries' => 5,
            ],
            [
                'movie_name' => 'Interstellar',
                'describe' => 'Trong bối cảnh trái đất đang cạn kiệt tài nguyên, một nhóm phi hành gia du hành qua một hố đen vũ trụ để tìm kiếm hành tinh mới có thể duy trì sự sống cho nhân loại.',
                'category' => 'Khoa học viễn tưởng',
                'images' => 'images/interstellar.jpg',
                'video' => 'video/interstellar.mp4',
                'age_limit' => false,
                'id_countries' => 6,
            ],
            [
                'movie_name' => 'Arrival',
                'describe' => 'Khi các phi thuyền ngoài hành tinh xuất hiện trên khắp thế giới, một nhà ngôn ngữ học được tuyển dụng để giao tiếp với người ngoài hành tinh và hiểu được mục đích của họ.',
                'category' => 'Khoa học viễn tưởng',
                'images' => 'images/arrival.jpg',
                'video' => 'video/arrivaltrailer.mp4',
                'age_limit' => false,
                'id_countries' => 7,
            ],
            [
                'movie_name' => 'Get Out',
                'describe' => 'Một người đàn ông da đen phát hiện ra những bí mật kinh hoàng khi thăm nhà của bạn gái người da trắng ở vùng ngoại ô.',
                'category' => 'Kinh dị',
                'images' => 'images/getout.jpg',
                'video' => 'video/getout.mp4',
                'age_limit' => true,
                'id_countries' => 8,
            ],
            [
                'movie_name' => 'Black Panther',
                'describe' => 'Challa trở về nhà để trở thành vua của Wakanda, nhưng phải đối mặt với những thách thức từ kẻ thù mạnh mẽ nhằm lật đổ ngôi vị của anh.',
                'category' => 'Khoa học viễn tưởng',
                'images' => 'images/blackpanther.jpg',
                'video' => 'video/blackpanther.mp4',
                'age_limit' => false,
                'id_countries' => 1,
            ],
            [
                'movie_name' => 'Avengers: Endgame',
                'describe' => 'Sau khi Thanos hủy diệt một nửa vũ trụ, các siêu anh hùng còn lại phải hợp sức để đảo ngược hành động của hắn và cứu lấy nhân loại.',
                'category' => 'Khoa học viễn tưởng',
                'images' => 'images/avengersendgame.jpg',
                'video' => 'video/avengersendgame.mp4',
                'age_limit' => false,
                'id_countries' => 2,
            ],
            [
                'movie_name' => 'Joker',
                'describe' => 'Câu chuyện về sự biến đổi của Arthur Fleck từ một diễn viên hài thất bại thành kẻ thù nguy hiểm nhất của Gotham, Joker.',
                'category' => 'Hình sự',
                'images' => 'images/joker.jpg',
                'video' => 'video/joker.mp4',
                'age_limit' => true,
                'id_countries' => 3,
            ],
            [
                'movie_name' => 'Gravity',
                'describe' => 'Hai phi hành gia cố gắng sống sót trong không gian khi tàu vũ trụ của họ bị phá hủy, để lại họ lơ lửng trong không gian mênh mông.',
                'category' => 'Khoa học viễn tưởng',
                'images' => 'images/gravity.jpg',
                'video' => 'video/gravity.mp4',
                'age_limit' => false,
                'id_countries' => 4,
            ],
            [
                'movie_name' => 'The Irishman',
                'describe' => 'Một sát thủ có liên hệ với đám đông hồi tưởng về sự nghiệp của mình và sự liên quan của ông đến vụ biến mất bí ẩn của Jimmy Hoffa.',
                'category' => 'Hình sự',
                'images' => 'images/theirishman.jpg',
                'video' => 'video/theirishman.mp4',
                'age_limit' => true,
                'id_countries' => 5,
            ],
            [
                'movie_name' => 'Roma',
                'describe' => 'Một người giúp việc cho một gia đình trung lưu tại thành phố Mexico vào những năm 1970 phải đối mặt với nhiều thách thức cá nhân và xã hội.',
                'category' => 'Roma',
                'images' => 'images/roma.jpg',
                'video' => 'video/roma.mp4',
                'age_limit' => false,
                'id_countries' => 6,
            ],
            [
                'movie_name' => 'Shin: Quyết chiến ! Vương quốc Rakuga và bốn vị hiệp sĩ',
                'describe' => 'Trong cuộc phiêu lưu này, Shin-chan và nhóm bạn bị cuốn vào Vương Quốc Rakuga, một thế giới kỳ lạ nơi mà nghệ thuật và hài hước là quyền lực chủ chốt.',
                'category' => 'Hoạt hình',
                'images' => 'images/shinmovie28.jpg',
                'video' => 'video/shinmovie28.mp4',
                'age_limit' => false,
                'id_countries' => 7,
            ],
            [
                'movie_name' => 'Shin: Bí ẩn bao trùm! Những bông hoa học viện Tenkazu',
                'describe' => 'Khi gia đình Nohara tham gia chuyến thăm học viện Tenkazu, họ không ngờ rằng sẽ dính vào một loạt sự kiện bí ẩn.',
                'category' => 'Hoạt hình',
                'images' => 'images/shinmovie29.jpg',
                'video' => 'video/shinmovie29.mp4',
                'age_limit' => false,
                'id_countries' => 8,
            ],
            [
                'movie_name' => 'Doraemon: Nobita và Mặt Trăng phiêu lưu ký',
                'describe' => 'Trên tàu vũ trụ "Lunar" của Doraemon, Nobita và nhóm bạn bè của mình bắt đầu cuộc hành trình tới Mặt Trăng.',
                'category' => 'Hoạt hình',
                'images' => 'images/doraemonmovie39.jpg',
                'video' => 'video/doraemonmovie39.mp4',
                'age_limit' => false,
                'id_countries' => 1,
            ],
            [
                'movie_name' => 'Doraemon: Nobita và những hiệp sĩ không gian',
                'describe' => 'Nobita và nhóm bạn bè của mình, cùng với Doraemon và bí ẩn người ngoài hành tinh Chamii, bắt đầu cuộc hành trình đến hành tinh Chamii.',
                'category' => 'Hoạt hình',
                'images' => 'images/doraemonmovie35.jpg',
                'video' => 'video/doraemonmovie35.mp4',
                'age_limit' => false,
                'id_countries' => 2,
            ],
            [
                'movie_name' => 'Doraemon: Nobita và cuộc chiến vũ trụ tí hon 2021',
                'describe' => 'Trong bộ phim này, Nobita và nhóm bạn bè của mình phát hiện ra một hành tinh nhỏ nhắn, nơi một cuộc chiến vũ trụ đang diễn ra.',
                'category' => 'Hoạt hình',
                'images' => 'images/doraemonmovie41.jpg',
                'video' => 'video/doraemonmovie41.mp4',
                'age_limit' => false,
                'id_countries' => 3,
            ],
            [
                'movie_name' => 'Conan: Viên đạn đỏ',
                'describe' => 'Trong "Viên Đạn Đỏ", Conan và nhóm bạn của mình phải giải quyết một vụ án liên quan đến một viên đạn đỏ có sức mạnh đặc biệt.',
                'category' => 'Hoạt hình',
                'images' => 'images/conanmovie24.jpg',
                'video' => 'video/conanmovie24.mp4',
                'age_limit' => false,
                'id_countries' => 4,
            ],
        ];
        DB::table('movie')->insert($movies);
    }
}
